#!/bin/bash
if [ $(git log -1 --oneline --pretty=format:'%s' | grep -e '^\[WIP\]') ]
then
  last_commit=`git log -1 --date=raw --pretty=format:"%ad"`
  current_commit=$GIT_AUTHOR_DATE
  [ "$(echo "$current_commit" | grep "$last_commit")" ] && exit 0 || echo "last commit is wip commit!!";exit 1
fi
