[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap <silent> <Space><Space> :<C-u>Denite file/rec<CR>
'''

hook_source = '''
call denite#custom#source('file/rec', 'matchers', ['matcher_fuzzy', 'matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [ '.cache/', 'repos/', 'node_modules'])

call denite#custom#option('default', {
    \ 'split': 'floating',
    \ })

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
nnoremap <silent><buffer><expr> <CR>
\ denite#do_map('do_action')
nnoremap <silent><buffer><expr> q
\ denite#do_map('quit')
nnoremap <silent><buffer><expr> p
\ denite#do_map('do_action', 'preview')
nnoremap <silent><buffer><expr> i
\ denite#do_map('open_filter_buffer')
endfunction
'''

