[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
	nnoremap <silent> <Space><Space> :<C-u>Denite file_rec<CR>
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'wombat'
    \ }
'''

[[plugins]]
	repo = 'cespare/vim-toml'
	on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'jszakmeister/markdown2ctags'
hook_add = '''
let g:tagbar_type_markdown = {
    \ 'ctagstype': 'markdown',
    \ 'ctagsbin' : '~/dotfiles/.cache/dein/repos/github.com/jszakmeister/markdown2ctags/markdown2ctags.py',
    \ 'ctagsargs' : '-f - --sort=yes',
    \ 'kinds' : [
        \ 's:sections',
        \ 'i:images'
    \ ],
    \ 'sro' : '|',
    \ 'kind2scope' : {
        \ 's' : 'section',
    \ },
    \ 'sort': 0,
\ }
'''

[[plugins]]
repo = 'violetyk/iikanji-markdown.vim'

[[plugins]]
repo = 'fatih/vim-go'
